name: doip_rw_tokio

on:
  push:
    branches: [ "main", "next" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --all-targets --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run docs
      run: cargo doc --verbose
